### ISSUE TITLE
Notifications and BetterTTV

### ISSUE THREAD

**Issue by wilflare** [Ndragomirov/twitch-now#103]
Sorry to bother but I'm a little confused.
(1) Dependency - Is Twitch Now independent of the notification settings in Twitch? I can't seem to find an option to enable just notification in Twitch (there's only Mobile Push and Email available)
(2) BetterTTV Notifications - Will Twitch Now conflict with BetterTTV? I use BetterTTV for Dark Theme

**Comment by Ndragomirov** [comment]
Hi,

1) twitch now doesnt depend on twitch notifications settings.
2) twitch now is not injecting scripts/modifing html code on twitch website, so it should work without any problems.

**Comment by wilflare** [comment]
thanks for the reply @Ndragomirov !
just two more questions
(1) Does the "Play sound notification" in Settings overwrite those in Manage Notifications?
(2) How long does each notification display and can we manage that interval? Would they appear under Chrome's notification bell in the Taskbar?

**Comment by valkyr9991234** [comment]
@wilflare 
(1) Browser always overwrites API settings
(2) Never asked myself that, 100% of users press X all the time xD

**Comment by wilflare** [comment]
@valkyr9991234 
thanks for the reply!
(1) hmm I was referring to the extension itself - there's "Settings" and "Manage Notifications" within the extension right? or am I confused
(2) hehe think it'll be useful!

**Comment by Ndragomirov** [comment]
@wilflare 

1) "Play sound notification" setting has priority over "Manage Notifications" settings.
2) around 10 sec. Current there is no option to change the delay of desktop notifications. Notifications would appear in taskbar only for 10 seconds.

**Comment by wilflare** [comment]
thanks so much @Ndragomirov and @valkyr9991234 
this really clarifies and helps!
(1) so if "Play sound notification" setting is unchecked, there will be no sound even in "Manage Notifications"?
(2) I really hope there will be such an option in the future!

(3) Chrome Notification Bell in the Taskbar - If I remember correctly, Chrome subsumes certain notifications under the Notification Bell icon under the Taskbar. Will Twitch Now be able to do that in the future?

**Comment by wilflare** [comment]
sorry to bother again but just to check @Ndragomirov 
does Twitch Now show any notifications while the Twitch tab is the Focus Tab?
something like BetterTTV here? http://t.co/rIqf7jJi8w

**Comment by Ndragomirov** [comment]
@wilflare 1) you are right
2) I hope too :3
3)  Notifications would appear in taskbar only for 10 seconds.


Twitch Now doesnt show any notifications on focus tab
