### ISSUE TITLE
Upload Firefox addon to addons.mozilla.org (Addon not signed)

### ISSUE THREAD

**Issue by CReimer** [Ndragomirov/twitch-now#106]
Could you please upload your Firefox addon to addons.mozilla.org.

Firefox keeps telling me that your addon is not properly signed. AFAIK you have to upload your addon to mozilla to get it signed.

**Comment by CReimer** [comment]
From this day on Firefox actively blocks Twitch Now. Please upload your addon to addons.mozilla.org.

**Comment by SW1FT** [comment]
I subscribe to this, please upload it to AMO.

**Comment by Ndragomirov** [comment]
Uploaded to addons.mozilla.org for review

**Comment by SW1FT** [comment]
Can you link us to the addon page?

**Comment by Ndragomirov** [comment]
![2](https://cloud.githubusercontent.com/assets/543401/9307769/671ea5a6-4511-11e5-95d7-78a28047b8eb.png)

Sit tight, it will take around 3-4 weeks to complete the review proccess.

**Comment by Ndragomirov** [comment]
should be available on https://addons.mozilla.org/en-US/firefox/addon/twitch-now/
