### ISSUE TITLE
Segoe UI Emoji font not displaying on stream title

### ISSUE THREAD

**Issue by SW1FT** [Ndragomirov/twitch-now#108]
An image is better to illustrate this issue, so here it goes:
![twitch now bug](https://cloud.githubusercontent.com/assets/6627739/9295123/f2891d7c-445a-11e5-9083-7e035a0f2d0d.png)

**Comment by Ndragomirov** [comment]
Not sure that Arial/Helvetica has support for this characters.

**Comment by SW1FT** [comment]
It doesn't because it's part of other font, Segoe UI Emoji.

**Comment by SW1FT** [comment]
Weird, the font is displaying nicely now, somehow it fixed itself...
