### ISSUE TITLE
After last update of Opera. Stopped working.

### ISSUE THREAD

**Issue by sadettin55** [Ndragomirov/twitch-now#131]
After the last update of Windows 10.
Opera is stopped working most the time when twitch now trying to use notification sound.

I was fast enough to disable it before opera crashed.
Need a quick update or something to fix this.

**Comment by Ndragomirov** [comment]
Will look into it, for now you can just disable, then reinstall the extension ( sound notifications are turned off by default )

**Comment by sadettin55** [comment]
Thank you.
Now it's okay. Waiting for an update.

**Comment by sadettin55** [comment]
New update!

Even if i disabled sound notifications there is still crash sometimes.
So i disable twitch now.
Using opera in this way for 4 day and not a single crash since.

**Comment by Ndragomirov** [comment]
@sadettin55  Just tested it on win10 x64 Home edition with Opera v34 and it works. Can you copy/paste a browser info from this page: browser://about

**Comment by sadettin55** [comment]
It's Turkish so i'm translating.


Sürüm(versiyon):	34.0.2036.25 - Opera güncel
Güncelleştirme kanalı (Update channel):	Stable
Sistem (Operation System):	Windows 10 64-bit (WoW64)
Tarayıcı kimliği (Scanner id)

Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.73 Safari/537.36 OPR/34.0.2036.25

Yollar(Paths)

Kurulum(setup path?!?):	C:\Program Files (x86)\Opera
Profil(profile):	C:\Users\Emirhan\AppData\Roaming\Opera Software\Opera Stable
Önbellek (cache):	C:\Users\Emirhan\AppData\Local\Opera Software\Opera Stable

**Comment by Ndragomirov** [comment]
@sadettin55 Do you use 2 or more monitors ?

**Comment by sadettin55** [comment]
nope

**Comment by Ndragomirov** [comment]
@sadettin55 what other extensions installed on opera ? :octocat:

**Comment by sadettin55** [comment]
AdBlock https://addons.opera.com/extensions/details/app_id/aobdicepooefnbaeokijohmhjlleamfj

BetterTTV

FVD Video Downloader https://addons.opera.com/extensions/details/app_id/neacgcjokggofibnbfapeaejhclmpple

IDM Integration Module

Looper for YouTube https://addons.opera.com/extensions/details/app_id/mdgbdahddgcdopcjhhalbmonbinihbbo

ZenMate
https://addons.opera.com/extensions/details/app_id/cnhbkkedmelfmalgjpkngiaoifpdfcnl

**Comment by Ndragomirov** [comment]
@sadettin55  related to this issue:

Hi! muratservan commented the report on Twitch Now v.1.1.180 at 06 Ocak 2016 01:20:10:

You are probably using Windows 10. If your action center disabled it causes some extensions which has desktop notification feature to crash Opera. SurfEasy also do that. So in short its not Twtich Now's problem.

**Comment by Vrakfall** [comment]
Looks completely fine Linux, using Opera-Next.

**Comment by xbliss** [comment]
@sadettin55  - Great suggestions - Saved.
