### ISSUE TITLE
Can't change language

### ISSUE THREAD

**Issue by ghost** [Ndragomirov/twitch-now#150]
It would be nice if we could choose the language we want

**Comment by Narno** [comment]
Hello @Scellow,

A short answer:
> The point of the built-in chrome.i18n API is to make extensions match the UI language of the browser so there's no chrome API way to change it programmatically

Source: http://stackoverflow.com/a/33390207/410850

**Comment by Scellow** [comment]
My browser is in English, but the extension still use french, anyways, i removed it, i made my own desktop notifier, don't wanna rely on the browser anymore
