### ISSUE TITLE
Make Twitch Now compatible with e10s on Firefox

### ISSUE THREAD

**Issue by SW1FT** [Ndragomirov/twitch-now#153]
Title ^

**Comment by Ndragomirov** [comment]
Will look into it thanks

**Comment by Ndragomirov** [comment]
fixed in 2978fb2d9a22c87f14c2a87344f903b093a439a8

**Comment by SW1FT** [comment]
@Ndragomirov Could you add the new version to the development channel in AMO, so people can test it without having to build?
