### ISSUE TITLE
Access extension as a tab

### ISSUE THREAD

**Issue by denolfe** [Ndragomirov/twitch-now#155]
Is it possible to access the extension as a new tab instead of clicking on the extension's icon?

I am attempting a sort of twitch kiosk with a raspberry pi, and this would be a much better stream browsing experience instead of the main site. 

I'd love to implement controls via arrow keys if the above were possible. Thanks!

**Comment by Ndragomirov** [comment]
Hi, you can access popup page using this link:  chrome-extension://nlmbdmpjmlijibeockamioakdpmhjnpk/common/html/popup.html#following
Its looks ugly because css styles are not adjusted for full window size

**Comment by denolfe** [comment]
This is what I was looking for, thanks!
