### ISSUE TITLE
Twitch Now disabled in Firefox Nightly

### ISSUE THREAD

**Issue by SW1FT** [Ndragomirov/twitch-now#171]
![tn](https://cloud.githubusercontent.com/assets/6627739/25715393/39725a9c-30f3-11e7-8dff-66b517eb8876.png)
"Twitch Now has been disabled since it is not multiprocess compatible."

https://wiki.mozilla.org/Add-ons/ShimsNightly

**Comment by Ndragomirov** [comment]
Hi, its  already been fixed in 2978fb2d9a22c87f14c2a87344f903b093a439a8

**Comment by SW1FT** [comment]
Can you upload the new version to AMO?

**Comment by SW1FT** [comment]
@Ndragomirov Still disabled, specially now that Firefox 54 (release) has multiprocess enabled. Please upload the new version on [AMO](https://addons.mozilla.org/).

**Comment by SW1FT** [comment]
@Ndragomirov Just installed the Chrome version on Firefox (using [Chrome Store Foxified](https://addons.mozilla.org/firefox/addon/chrome-store-foxified)) and everything works perfectly so far, besides a [minor issue](https://i.imgur.com/0hMTtmf.png). You could just port it to Firefox without changing much. Just care about a couple warnings that AMO pointed out when I signed the Chrome add-on:

> **/permissions: Unknown permissions "background" at 1.**
Warning: See https://mzl.la/1R1n1t0 (MDN Docs) for more information.
_manifest.json_

> **"content_security_policy" is defined in the manifest.json**
Warning: A custom content_security_policy needs additional review.

> **eval can be harmful.**
Warning: Evaluation of strings as code can lead to security vulnerabilities and performance issues, even in the most innocuous of circumstances. Please avoid using `eval` and the `Function` constructor when at all possible.'
_common/lib/3rd/jquery.js line 315 column 15_

> **Unsafe assignment to innerHTML**
Warning: Due to both security and performance concerns, this may not be set using dynamic values which have not been adequately sanitized. This can lead to security issues or fairly serious performance degradation.
_common/lib/3rd/jquery.js line 5089 column 6_

> **Unsafe assignment to innerHTML**
Warning: Due to both security and performance concerns, this may not be set using dynamic values which have not been adequately sanitized. This can lead to security issues or fairly serious performance degradation.
_common/lib/3rd/jquery.js line 5298 column 8_

> **eval can be harmful.**
Warning: Evaluation of strings as code can lead to security vulnerabilities and performance issues, even in the most innocuous of circumstances. Please avoid using `eval` and the `Function` constructor when at all possible.'
_common/dist/popup.comb.js line 432 column 15_

> **Unsafe assignment to innerHTML**
Warning: Due to both security and performance concerns, this may not be set using dynamic values which have not been adequately sanitized. This can lead to security issues or fairly serious performance degradation.
_common/dist/popup.comb.js line 5206 column 6_

> **Unsafe assignment to innerHTML**
Warning: Due to both security and performance concerns, this may not be set using dynamic values which have not been adequately sanitized. This can lead to security issues or fairly serious performance degradation.
_common/dist/popup.comb.js line 5415 column 8_

> **The Function constructor is eval.**
Warning: Evaluation of strings as code can lead to security vulnerabilities and performance issues, even in the most innocuous of circumstances. Please avoid using `eval` and the `Function` constructor when at all possible.'
_common/dist/popup.comb.js line 12716 column 20_

> **The "update_url" property is not used by Firefox.**
Warning: The "update_url" is not used by Firefox in the root of a manifest; your add-on will be updated via the Add-ons site and not your "update_url". See: https://mzl.la/25zqk4O
_manifest.json_

> **Known JS library detected**
Warning: JavaScript libraries are discouraged for simple add-ons, but are generally accepted.
_common/lib/3rd/underscore.js_

**Comment by dpeukert** [comment]
@Ndragomirov I recently switched to Firefox Nightly and I would like to use this extension. Can you upload the new version?

**Comment by SW1FT** [comment]
Firefox Nightly 57 only allows WebExtensions, if anyone wants to use Twitch Now's Chrome version, you can get it from [here](https://www.dropbox.com/s/8oxmcwmo1nzrd35/nlmbdmpjmlijibeockamioakdpmhjnpk%40chrome-store-foxified-unsigned.xpi?dl=0).

**Comment by SW1FT** [comment]
1.1.197 was just released. Closing this issue.
