### ISSUE TITLE
[Feature] Language filter

### ISSUE THREAD

**Issue by PhilJbt** [Ndragomirov/twitch-now#174]
It would be great if we could filter popular streams by language.

**Comment by SW1FT** [comment]
That feature already exists (see https://github.com/Ndragomirov/twitch-now/commit/fdc0c7594d0b9da888bb46a009c453e9387037b4, https://github.com/Ndragomirov/twitch-now/commit/b8d0aaf9a3128547874c1d8b1e0c8eeffed68501 and https://github.com/Ndragomirov/twitch-now/commit/7743dfa466b2912a6ceb702293e2c70e2bf2526c). We just have to wait for @Ndragomirov to update twitch now in all extension stores.
