### ISSUE TITLE
[Suggestion] Ability to remove VODcast streams from overview

### ISSUE THREAD

**Issue by karbowiak** [Ndragomirov/twitch-now#176]
As the title says, would it be possible to filter out not-live-vodcast channels from the list view? :)

**Comment by bogenpirat** [comment]
if you use [this](https://dev.twitch.tv/docs/v5/reference/streams/#get-live-streams) endpoint, you should be able to filter for the respective stream's `stream_type` attribute. just filtering through query parameter for `live` doesn't seem to work; a stream i tested it for shows `stream_type: "watch_party"` as a VOD cast, but does show up in the response if filtered with `&stream_type=live`. so you'll probably still have to iterate over the returned streams collection.

**Comment by Ndragomirov** [comment]
should be fixed in 4926f14d2caf887690b238e849ca2321ca474c32
