### ISSUE TITLE
Not working auto update subscriptions on Firefox 55

### ISSUE THREAD

**Issue by r57zone** [Ndragomirov/twitch-now#183]
Addon stopped signaling about new streams until I manually update the list of subscriptions. It seems to stop working after the Firefox update (v55).

**Comment by r57zone** [comment]
It seems fixed.

**Comment by Ndragomirov** [comment]
should be fixed in 1.1.199

**Comment by r57zone** [comment]
К сожалению, нет, при каждом запуске авторизация теряется, и необходимо нажимать кнопку "Войти", что были уведомления.
Firefox 56.
