### ISSUE TITLE
Missing stream thumbnails

### ISSUE THREAD

**Issue by ObiWanTwo** [Ndragomirov/twitch-now#246]
Today I started noticing that video thumbnails were missing for some streams. This happens on all streams from all tabs and refreshing the tab does not help.
The issue does not seem to disappear by reinstalling the extension too. In fact the same exact streams are missing thumbnails/previews.
I am running the extension on Firefox 80.0.1 (64-bit).

![Violet thumbnail on some streams](https://i.imgur.com/QUpIhUK.png)

**Comment by Paynmayn** [comment]
I think this is an issue at Twitch, and not in this extension. I get the same problem at twitch.tv on the same stream image previews as you do.
