### ISSUE TITLE
Connection error to extension

### ISSUE THREAD

**Issue by louis-mps** [Ndragomirov/twitch-now#270]
The extension stopped working on March 29, 2022, so I decided to delete it and extract again the file. When I try to log in, I have an error message : "{"status":500,"message":"invalid authorization"}" and I do not know if it's only me.

Thank you.

macOS Monterey 12.1 (21C52)
Chrome 100.0.4896.60 (Build officiel) (x86_64)

**Comment by Mpc46** [comment]
Yeah, and the other alternatives are dead aswell, I belive the twitch API got yeeted... really harshly

**Comment by louis-mps** [comment]
> Yeah, and the other alternatives are dead aswell, I belive the twitch API got yeeted... really harshly

I’m using Gumbo Twitch Companion meanwhile, but there is no sound notification, feature which I liked best with Twitch Now

**Comment by aviv0404** [comment]
#267 @zm3y fixed it 3 hours ago, build their version

**Comment by louis-mps** [comment]
> #267 @zm3y fixed it 3 hours ago, build their version

Thanks

**Comment by louis-mps** [comment]
@aviv0404 Sorry I'm new to github and I don't really understand how to instal @zm3y version

**Comment by aviv0404** [comment]
> @aviv0404 Sorry I'm new to github and I don't really understand how to instal @zm3y version

1) Install Node js
2) run "npm install --global gulp-cli" in cmd to install Gulp
3) On zm3y's fork press Code -> Download Zip and extract somewhere
4) Open cmd and navigate to the location you extracted at 
5) Run "npm install"
6) Run "gulp chrome" (other options are "gulp firefox" and "gulp opera"
7) Load an unpacked extension in chrome/firefox/opera and add the corresponding folder in ...\twitch-now-master\build

P.S. firefox has another step, see readme

**Comment by louis-mps** [comment]
> > @aviv0404 Sorry I'm new to github and I don't really understand how to instal @zm3y version
> 
> 1. Install Node js
> 2. run "npm install --global gulp-cli" in cmd to install Gulp
> 3. On zm3y's fork press Code -> Download Zip and extract somewhere
> 4. Open cmd and navigate to the location you extracted at
> 5. Run npm install
> 6. Run "gulp chrome" (other options are "Gulp firefox" and "Gulp opera"
> 7. Load an unpacked extension in chrome/firefox/opera and add the corresponding folder in ...\twitch-now-master\build
> 
> P.S. firefox has another step, see readme

Thanks

**Comment by zm3y** [comment]
@louis-mps you can use prebuilded version. Watch video. I hope it was helpful.

https://user-images.githubusercontent.com/8388687/160924023-85410df3-7bcd-4b21-accb-3884d98a1599.mp4

**Comment by louis-mps** [comment]
@zm3y Works perfect! Thanks

**Comment by JBZezinho** [comment]
For those who use Microsoft Edge as a Browser, To Install and Just Go to
... (3 Points) Underneath the X (Close Browser)
extensions
manage Extensions
Go to Load without package
select the folder
and the Extension will now be installed
and Just Go to the Extension and authorize the Extension to be Used to Work

**Comment by demonzinho** [comment]
hello and for edge ? help please
