### ISSUE TITLE
Channel thumbnails don't load until mouseover

### ISSUE THREAD

**Issue by OlsonDev** [Ndragomirov/twitch-now#64]
I'm not sure if this is intentional or not but I find it annoying that clicking the extension icon opens the popup, shows channels in a list, but doesn't show the thumbnails until I mouseover the popup. If this is intentional, an option in the settings to tweak this would be nice.

![twitchnowbroken](https://cloud.githubusercontent.com/assets/308072/5307327/b5fad528-7bd1-11e4-99fa-e515f5b0e076.png)

Also, thanks for the great extension! :-)

**Comment by ExorcistF1** [comment]
Есть возможность в опции добавить эти изменения?
