### ISSUE TITLE
Add favorite games tab

### ISSUE THREAD

**Issue by Ndragomirov** [Ndragomirov/twitch-now#65]
http://api.twitch.tv/api/users/sunspots/follows/games

**Comment by Ndragomirov** [comment]
Not sure whats is better: adding new tab only for favorite games or add favorite games to existing `browse games` tab

**Comment by ExorcistF1** [comment]
Adding new tab i think, it all depends on the number of games, such as fan final fantasy tab will turn into a "favorite games" and he will lose the main purpose of the tab "browse game"

**Comment by Ndragomirov** [comment]
Fixed 033a03dad8c6aac229c137a8206de62ec7473a30
