### ISSUE TITLE
Plugin for firefox 35.0

### ISSUE THREAD

**Issue by jsynth** [Ndragomirov/twitch-now#73]
Any fix for firefox plugin? I think it's broken\outdated.

**Comment by Ndragomirov** [comment]
hi, check this build: https://docs.google.com/file/d/0BykW-NfUUzm5Z2RCWmcxTmQ5cEk/edit

**Comment by jsynth** [comment]
// Where is my manners, Greetings fellow!

Works for me, thanks alot!
