### ISSUE TITLE
Stream language preferences

### ISSUE THREAD

**Issue by Ndragomirov** [Ndragomirov/twitch-now#87]
Need some good looking svg flag images ( pref 24x24, 32x32 px sizes )

**Comment by Ndragomirov** [comment]
![language](https://cloud.githubusercontent.com/assets/543401/11449292/eca61e94-9588-11e5-9526-f7a202e934b8.jpg)

**Comment by Narno** [comment]
For memory: https://github.com/Ndragomirov/twitch-now/blob/master/templates/gameextended.html#L20
